// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD75iX_tm51iLgeEKRsPKVO0zWn8DPYBAE',
    appId: '1:114499353319:web:a7e3f2c17743dba60c0042',
    messagingSenderId: '114499353319',
    projectId: 'chatapp-1ced9',
    authDomain: 'chatapp-1ced9.firebaseapp.com',
    storageBucket: 'chatapp-1ced9.firebasestorage.app',
    measurementId: 'G-LH3XHTFNHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUnGgU12RWE-AKRHGFneQoaIb9CawW2NU',
    appId: '1:114499353319:android:1d64a102a2779e3e0c0042',
    messagingSenderId: '114499353319',
    projectId: 'chatapp-1ced9',
    storageBucket: 'chatapp-1ced9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTdIdincyKjFAel1G4rR8ggSctE05wTyM',
    appId: '1:114499353319:ios:87f1b975c51a0c000c0042',
    messagingSenderId: '114499353319',
    projectId: 'chatapp-1ced9',
    storageBucket: 'chatapp-1ced9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTdIdincyKjFAel1G4rR8ggSctE05wTyM',
    appId: '1:114499353319:ios:87f1b975c51a0c000c0042',
    messagingSenderId: '114499353319',
    projectId: 'chatapp-1ced9',
    storageBucket: 'chatapp-1ced9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD75iX_tm51iLgeEKRsPKVO0zWn8DPYBAE',
    appId: '1:114499353319:web:fbeb07b3c8de5db90c0042',
    messagingSenderId: '114499353319',
    projectId: 'chatapp-1ced9',
    authDomain: 'chatapp-1ced9.firebaseapp.com',
    storageBucket: 'chatapp-1ced9.firebasestorage.app',
    measurementId: 'G-K6YRDM04FH',
  );

}